# Generated by Django 3.1.2 on 2020-11-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingmodel',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='ratingmodel',
            name='company',
        ),
        migrations.DeleteModel(
            name='ProfileViewDetails',
        ),
        migrations.DeleteModel(
            name='RatingModel',
        ),
    ]
